const dummyData = {
    
    categories: [
        { name: "Burgers", description: "Juicy grilled burgers" },
        { name: "Pizzas", description: "Oven-baked cheesy pizzas" },
        { name: "Burritos", description: "Rolled Mexican delights" },
        { name: "Sandwiches", description: "Stacked and stuffed sandwiches" },
        { name: "Wraps", description: "Rolled up wraps packed with flavor" },
        { name: "Bowls", description: "Balanced rice and protein bowls" },
    ],

    customizations: [
        // Toppings
        { name: "Avocado", imageKey: "avocado", price: 2.25, type: "topping" },
        { name: "Bacon", imageKey: "bacon", price: 1.95, type: "topping" },
        { name: "Cheese", imageKey: "cheese", price: 1.25, type: "topping" },
        { name: "Jalapeños", imageKey: "jalapenos", price: 0.50, type: "topping" },
        { name: "Onions", imageKey: "onions", price: 0.75, type: "topping" },
        { name: "Olives", imageKey: "olives", price: 0.40, type: "topping" },
        { name: "Mushrooms", imageKey: "mushrooms", price: 1.15, type: "topping" },
        { name: "Tomatoes  ", imageKey: "tomatoes", price: 0.95, type: "topping" },
        { name: "Cucumber", imageKey: "cucumber", price: 0.50, type: "topping" },
        { name: "Lettuce", imageKey: "lettuce", price: 0.65, type: "topping" },

        // Sides
        { name: "Chicken Nuggets", imageKey: "chickenNuggets", price: 5.99, type: "side" },
        { name: "Choco Lava Cake", imageKey: "chocoLavaCake", price: 6.50, type: "side" },
        { name: "Cola", imageKey: "cola", price: 2.25, type: "side" },
        { name: "Coleslaw", imageKey: "coleslaw", price: 1.99, type: "side" },
        { name: "Fries", imageKey: "fries", price: 3.25, type: "side" },
        { name: "Garlic Bread", imageKey: "garlicBread", price: 4.50, type: "side" },
        { name: "Iced Tea", imageKey: "icedTea", price: 2.50, type: "side" },
        { name: "Mozzarella Sticks", imageKey: "mozzarellaSticks", price: 6.99, type: "side" },
        { name: "Onion Rings", imageKey: "onionRings", price: 4.75, type: "side" },
        { name: "Potato Wedges", imageKey: "potatoWedges", price: 4.25, type: "side" },
        { name: "Salad", imageKey: "salad", price: 5.50, type: "side" },
        { name: "Sweet Corn", imageKey: "sweetCorn", price: 2.75, type: "side" },
    ],

    menu: [
        {
            name: "Classic Cheeseburger",
            slug: "classic-cheeseburger",
            description: "Beef patty, cheese, lettuce, tomato",
            image_url:
                "https://static.vecteezy.com/system/resources/previews/044/844/600/large_2x/homemade-fresh-tasty-burger-with-meat-and-cheese-classic-cheese-burger-and-vegetable-ai-generated-free-png.png",
            price: 25.99,
            rating: 4.5,
            calories: 550,
            protein: 25,
            category_name: "Burgers",
            customizations: ["Cheese", "Cola", "Fries", "Onions", "Bacon"],
        },
        {
            name: "Pepperoni Pizza",
            slug: "pepperoni-pizza",
            description: "Loaded with cheese and pepperoni slices",
            image_url:
                "https://static.vecteezy.com/system/resources/previews/023/742/417/large_2x/pepperoni-pizza-isolated-illustration-ai-generative-free-png.png",
            price: 30.99,
            rating: 4.7,
            calories: 700,
            protein: 30,
            category_name: "Pizzas",
            customizations: [
                "Cheese",
                "Jalapeños",
                "Garlic Bread",
                "Cola",
                "Olives",
            ],
        },
        {
            name: "Bean Burrito",
            slug: "bean-burrito",
            description: "Stuffed with beans, rice, salsa",
            image_url:
                "https://static.vecteezy.com/system/resources/previews/055/133/581/large_2x/deliciously-grilled-burritos-filled-with-beans-corn-and-fresh-vegetables-served-with-lime-wedge-and-cilantro-isolated-on-transparent-background-free-png.png",
            price: 20.99,
            rating: 4.2,
            calories: 480,
            protein: 18,
            category_name: "Burritos",
            customizations: ["Jalapeños", "Iced Tea", "Fries", "Salad"],
        },
        {
            name: "BBQ Bacon Burger",
            slug: "bbq-bacon-burger",
            description: "Smoky BBQ sauce, crispy bacon, cheddar",
            image_url:
                "https://static.vecteezy.com/system/resources/previews/060/236/245/large_2x/a-large-hamburger-with-cheese-onions-and-lettuce-free-png.png",
            price: 27.5,
            rating: 4.8,
            calories: 650,
            protein: 29,
            category_name: "Burgers",
            customizations: ["Onions", "Fries", "Cola", "Bacon", "Avocado"],
        },
        {
            name: "Chicken Caesar Wrap",
            slug: "chicken-caesar-wrap",
            description: "Grilled chicken, lettuce, Caesar dressing",
            image_url:
                "https://static.vecteezy.com/system/resources/previews/048/930/603/large_2x/caesar-wrap-grilled-chicken-isolated-on-transparent-background-free-png.png",
            price: 21.5,
            rating: 4.4,
            calories: 490,
            protein: 28,
            category_name: "Wraps",
            customizations: ["Cheese", "Cola", "Potato Wedges", "Tomatoes"],
        },
        {
            name: "Grilled Veggie Sandwich",
            slug: "grilled-veggie-sandwich",
            description: "Roasted veggies, pesto, cheese",
            image_url:
                "https://static.vecteezy.com/system/resources/previews/047/832/012/large_2x/grilled-sesame-seed-bread-veggie-sandwich-with-tomato-and-onion-free-png.png",
            price: 19.99,
            rating: 4.1,
            calories: 420,
            protein: 19,
            category_name: "Sandwiches",
            customizations: ["Mushrooms", "Olives", "Mozzarella Sticks", "Iced Tea"],
        },
        {
            name: "Double Patty Burger",
            slug: "double-patty-burger",
            description: "Two juicy beef patties and cheese",
            image_url:
                "https://static.vecteezy.com/system/resources/previews/060/359/627/large_2x/double-cheeseburger-with-lettuce-tomatoes-cheese-and-sesame-bun-free-png.png",
            price: 32.99,
            rating: 4.9,
            calories: 720,
            protein: 35,
            category_name: "Burgers",
            customizations: [
                "Cheese",
                "Onions",
                "Fries",
                "Cola",
                "Chicken Nuggets",
            ],
        },
        {
            name: "Paneer Tikka Wrap",
            slug: "paneer-tikka-wrap",
            description: "Spicy paneer, mint chutney, veggies",
            image_url:
                "https://static.vecteezy.com/system/resources/previews/057/913/530/large_2x/delicious-wraps-a-tantalizing-array-of-wraps-filled-with-vibrant-vegetables-succulent-fillings-and-fresh-ingredients-artfully-arranged-for-a-mouthwatering-culinary-experience-free-png.png",
            price: 23.99,
            rating: 4.6,
            calories: 470,
            protein: 20,
            category_name: "Wraps",
            customizations: ["Jalapeños", "Tomatoes", "Salad", "Fries", "Iced Tea"],
        },
        {
            name: "Mexican Burrito Bowl",
            slug: "mexican-burrito-bowl",
            description: "Rice, beans, corn, guac, salsa",
            image_url:
                "https://static.vecteezy.com/system/resources/previews/057/466/374/large_2x/healthy-quinoa-bowl-with-avocado-tomato-and-black-beans-ingredients-free-png.png",
            price: 26.49,
            rating: 4.7,
            calories: 610,
            protein: 24,
            category_name: "Bowls",
            customizations: ["Avocado", "Sweet Corn", "Salad", "Iced Tea"],
        },
        {
            name: "Spicy Chicken Sandwich",
            slug: "spicy-chicken-sandwich",
            description: "Crispy chicken, spicy sauce, pickles",
            image_url:
                "https://static.vecteezy.com/system/resources/previews/051/814/008/large_2x/a-grilled-chicken-sandwich-with-lettuce-and-tomatoes-free-png.png",
            price: 24.99,
            rating: 4.3,
            calories: 540,
            protein: 26,
            category_name: "Sandwiches",
            customizations: [
                "Jalapeños",
                "Onions",
                "Fries",
                "Cola",
                "Choco Lava Cake",
            ],
        },
        {
            name: "Classic Margherita Pizza",
            slug: "classic-margherita-pizza",
            description: "Tomato, mozzarella, fresh basil",
            image_url:
                "https://static.vecteezy.com/system/resources/previews/058/700/845/large_2x/free-isolated-on-transparent-background-delicious-pizza-topped-with-fresh-tomatoes-basil-and-melted-cheese-perfect-for-food-free-png.png",
            price: 26.99,
            rating: 4.1,
            calories: 590,
            protein: 21,
            category_name: "Pizzas",
            customizations: ["Cheese", "Olives", "Cola", "Garlic Bread"],
        },
        {
            name: "Protein Power Bowl",
            slug: "protein-power-bowl",
            description: "Grilled chicken, quinoa, veggies",
            image_url:
                "https://static.vecteezy.com/system/resources/previews/056/106/379/large_2x/top-view-salad-with-chicken-avocado-tomatoes-and-lettuce-free-png.png",
            price: 29.99,
            rating: 4.8,
            calories: 580,
            protein: 38,
            category_name: "Bowls",
            customizations: ["Avocado", "Salad", "Sweet Corn", "Iced Tea"],
        },
        {
            name: "Paneer Burrito",
            slug: "paneer-burrito",
            description: "Paneer cubes, spicy masala, rice, beans",
            image_url:
                "https://static.vecteezy.com/system/resources/previews/056/565/254/large_2x/burrito-with-cauliflower-and-vegetables-free-png.png",
            price: 24.99,
            rating: 4.2,
            calories: 510,
            protein: 22,
            category_name: "Burritos",
            customizations: ["Jalapeños", "Fries", "Garlic Bread", "Cola"],
        },
        {
            name: "Chicken Club Sandwich",
            slug: "chicken-club-sandwich",
            description: "Grilled chicken, lettuce, cheese, tomato",
            image_url:
                "https://static.vecteezy.com/system/resources/previews/060/364/135/large_2x/a-flavorful-club-sandwich-with-turkey-bacon-and-fresh-vegetables-sliced-and-isolated-on-a-transparent-background-free-png.png",
            price: 27.49,
            rating: 4.5,
            calories: 610,
            protein: 31,
            category_name: "Sandwiches",
            customizations: ["Bacon", "Tomatoes", "Mozzarella Sticks", "Iced Tea"],
        },
    ],
};

export default dummyData;